import { users, organizations, programs, cohorts, participants, expenses, sessions, attendance, certificates, curriculumModules } from '../mock-data/seed';
import { permissionGrants, can } from '../mock-data/permissions';
import { blogPosts, events, enrollments, venues, facilitatorProfiles, assessments, evaluations, appNotifications, eventRegistrations } from '../mock-data/content';
import { roles } from '../mock-data/roles';
import type { User, Program, Expense, Cohort, Action, Resource } from '../mock-data/types';
import {programSchema,cohortSchema,expenseSchema,userInviteSchema,contentSchema,blogSchema} from '../mock-data/validation';
import {ZodError} from 'zod';
import DOMPurify from 'dompurify';

export type ApiResult<T> = { ok: true; data: T; meta: { requestId: string; servedAt: string } } | { ok: false; error: { code: string; message: string; retryable: boolean }; meta: { requestId: string; servedAt: string } };
export interface ApiOptions { minDelayMs?: number; maxDelayMs?: number; errorRate?: number; }
let simulation: Required<ApiOptions> = { minDelayMs: 350, maxDelayMs: 850, errorRate: 0 };
export function configureMockApi(options: ApiOptions) { simulation = { ...simulation, ...options }; }
const delay=(ms:number)=>new Promise<void>(resolve=>setTimeout(resolve,ms));
const requestId=()=>`mock-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const key='wego.mock.data.v1';
const collections:Record<string,unknown[]>={organizations,users,programs,cohorts,participants,expenses,sessions,attendance,certificates,curriculumModules,blogPosts,events,enrollments,venues,facilitatorProfiles,assessments,evaluations,appNotifications,roles,permissionGrants,eventRegistrations};
let hydrated=false;
function hydrate(){if(hydrated||typeof localStorage==='undefined')return;hydrated=true;try{const raw=localStorage.getItem(key);if(!raw)return;const state=JSON.parse(raw) as Record<string,unknown[]>;for(const [name,target] of Object.entries(collections)){if(Array.isArray(state[name]))target.splice(0,target.length,...state[name]);}}catch{localStorage.removeItem(key)}}
function persist(){if(typeof localStorage==='undefined')return;try{localStorage.setItem(key,JSON.stringify(collections));}catch{/* Keep the in-memory demo usable if browser storage is full. */}}
export async function endpoint<T>(work:()=>T,options:ApiOptions={}):Promise<ApiResult<T>>{const cfg={...simulation,...options};await delay(cfg.minDelayMs+Math.floor(Math.random()*Math.max(0,cfg.maxDelayMs-cfg.minDelayMs)));const meta={requestId:requestId(),servedAt:new Date().toISOString()};if(Math.random()<cfg.errorRate)return{ok:false,error:{code:'MOCK_NETWORK_ERROR',message:'The demo service could not complete this request. Please try again.',retryable:true},meta};try{hydrate();const data=work();persist();return{ok:true,data,meta};}catch(error){const invalid=error instanceof Error&&error.message==='Invalid email or password';return{ok:false,error:{code:invalid?'INVALID_CREDENTIALS':'MOCK_SERVICE_ERROR',message:invalid?'Email or password is incorrect.':error instanceof ZodError?error.issues[0]?.message||'Please check the submitted fields.':error instanceof Error?error.message:'The demo service encountered an unexpected error.',retryable:false},meta};}}
function visible<T extends {organizationId:string}>(rows:T[],user:User):T[]{return user.organizationId===null?rows:rows.filter(row=>row.organizationId===user.organizationId)}
function visibleByPermission<T extends {organizationId:string;id:string}>(rows:T[],user:User,resource:Resource,owner?:(row:T)=>boolean):T[]{const tenant=visible(rows,user);return tenant.filter(row=>{const context={organizationId:user.organizationId||undefined,resourceOrganizationId:row.organizationId,assigned:assignedRecord(resource,row.id,user),self:owner?owner(row):row.id===user.id,coFunded:cofundedRecord(resource,row.id,user)};if(can(user,'view',resource,context))return true;switch(resource){case 'programs':return (row as any).public===true||enrollments.some(e=>e.participantId===user.id&&e.programId===row.id);case 'events':return (row as any).public===true&&(row as any).status==='upcoming';case 'blog':return (row as any).status==='published';default:return false;}})}
function assignedRecord(resource:Resource,recordId:string,user:User){if(resource==='programs')return (programs.find(p=>p.id===recordId)?.facilitatorIds||[]).includes(user.id);if(resource==='cohorts')return sessions.some(s=>s.cohortId===recordId&&s.facilitatorIds.includes(user.id));if(resource==='participants')return enrollments.some(e=>e.participantId===recordId&&programs.find(p=>p.id===e.programId)?.facilitatorIds.includes(user.id));if(resource==='attendance')return sessions.some(s=>s.id===recordId&&s.facilitatorIds.includes(user.id));if(resource==='certificates'){const cert=certificates.find(c=>c.id===recordId);return !!programs.find(p=>p.id===cert?.programId)?.facilitatorIds.includes(user.id)}if(resource==='assessments'){const row=assessments.find(a=>a.id===recordId);return !!row&&programAssigned(user,row.programId)}if(resource==='evaluations'){const row=evaluations.find(a=>a.id===recordId);return !!row&&programAssigned(user,row.programId)}if(resource==='curriculum'){const row=curriculumModules.find(a=>a.id===recordId);return !!row&&programAssigned(user,row.programId)}return false;}
function cofundedRecord(resource:Resource,recordId:string,user:User){const programId=resource==='programs'?recordId:resource==='cohorts'?cohorts.find(c=>c.id===recordId)?.programId:resource==='expenses'?expenses.find(e=>e.id===recordId)?.programId:resource==='participants'?enrollments.find(e=>e.participantId===recordId)?.programId:resource==='certificates'?certificates.find(c=>c.id===recordId)?.programId:resource==='assessments'?assessments.find(a=>a.id===recordId)?.programId:resource==='evaluations'?evaluations.find(a=>a.id===recordId)?.programId:resource==='curriculum'?curriculumModules.find(a=>a.id===recordId)?.programId:undefined;return !!programs.find(p=>p.id===programId)?.sponsorOrganizationIds?.includes(user.organizationId||'')}
function assertTenant(user:User,organizationId:string){if(user.organizationId!==null&&user.organizationId!==organizationId)throw new Error('This record is outside your organization.');}
function authorize(user:User,action:Action,resource:Resource,organizationId:string,scope:{assigned?:boolean;self?:boolean;coFunded?:boolean}={}){assertTenant(user,organizationId);if(!can(user,action,resource,{organizationId:user.organizationId||organizationId,resourceOrganizationId:organizationId,...scope}))throw new Error(`Permission denied: ${action} ${resource} is not granted to this account.`);}
function programAssigned(user:User,programId:string){return !!programs.find(p=>p.id===programId)?.facilitatorIds.includes(user.id)}
const id=(prefix:string)=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`;
export const mockApi={
 organizations:(user:User)=>endpoint(()=>user.organizationId===null?organizations:organizations.filter(o=>o.id===user.organizationId)),
 programs:(user:User)=>endpoint(()=>visibleByPermission(programs,user,'programs')),cohorts:(user:User)=>endpoint(()=>visibleByPermission(cohorts,user,'cohorts')),participants:(user:User)=>endpoint(()=>visibleByPermission(participants,user,'participants')),expenses:(user:User)=>endpoint(()=>visibleByPermission(expenses,user,'expenses',row=>row.participantId===user.id)),sessions:(user:User)=>endpoint(()=>visibleByPermission(sessions,user,'cohorts')), createSession:(user:User,record:Omit<(typeof sessions)[number],'id'>)=>endpoint(()=>{const parent=cohorts.find(c=>c.id===record.cohortId);if(!parent||parent.organizationId!==record.organizationId)throw new Error('Cohort not found in this organization.');if(record.facilitatorIds.some(fid=>!users.some(u=>u.id===fid&&u.organizationId===record.organizationId&&can(u,'view','cohorts',{organizationId:record.organizationId,resourceOrganizationId:record.organizationId,assigned:true}))))throw new Error('Every facilitator must be an active user in this organization.');if(record.venueId&&!venues.some(v=>v.id===record.venueId&&v.organizationId===record.organizationId))throw new Error('Choose a venue in this organization.');authorize(user,'edit','cohorts',record.organizationId,{assigned:record.facilitatorIds.includes(user.id)&&programAssigned(user,parent.programId)});const start=new Date(record.startsAt).getTime(),end=new Date(record.endsAt).getTime();if(!(start<end))throw new Error('Session end must occur after its start.');const overlaps=sessions.some(s=>s.organizationId===record.organizationId&&new Date(s.startsAt).getTime()<end&&new Date(s.endsAt).getTime()>start&&(s.facilitatorIds.some(f=>record.facilitatorIds.includes(f))||s.venueId&&s.venueId===record.venueId));if(overlaps)throw new Error('Scheduling conflict: the facilitator or venue is already booked for that time.');const row={...record,id:id('session')};sessions.push(row);return row;}),attendance:(user:User)=>endpoint(()=>visibleByPermission(attendance,user,'attendance',row=>row.participantId===user.id)),certificates:(user:User)=>endpoint(()=>visibleByPermission(certificates,user,'certificates',row=>row.participantId===user.id)),blogPosts:(user:User)=>endpoint(()=>visibleByPermission(blogPosts,user,'blog')),events:(user:User)=>endpoint(()=>visibleByPermission(events,user,'events')),
 assessments:(user:User)=>endpoint(()=>visibleByPermission(assessments,user,'assessments',row=>row.participantId===user.id)),evaluations:(user:User)=>endpoint(()=>visibleByPermission(evaluations,user,'evaluations',row=>row.participantId===user.id)),curriculumForUser:(user:User,programId:string)=>endpoint(()=>visibleByPermission(curriculumModules,user,'curriculum',row=>enrollments.some(e=>e.programId===row.programId&&e.participantId===user.id)).filter(m=>m.programId===programId)),notifications:(user:User)=>endpoint(()=>appNotifications.filter(n=>n.userId===user.id)),myEnrollments:(user:User)=>endpoint(()=>enrollments.filter(e=>e.participantId===user.id)),attendanceForMe:(user:User)=>endpoint(()=>attendance.filter(a=>a.participantId===user.id)),
 userDirectory:(user:User)=>endpoint(()=>{if(!can(user,'view','users',{organizationId:user.organizationId||undefined,resourceOrganizationId:user.organizationId||undefined})&&user.organizationId!==null)return[user];return user.organizationId===null?users:users.filter(u=>u.organizationId===user.organizationId)}),
 createProgram:(user:User,record:Omit<Program,'id'>)=>endpoint(()=>{programSchema.parse(record);authorize(user,'create','programs',record.organizationId);if(record.facilitatorIds.some(fid=>!users.some(u=>u.id===fid&&u.organizationId===record.organizationId&&can(u,'view','cohorts',{organizationId:record.organizationId,resourceOrganizationId:record.organizationId,assigned:true}))))throw new Error('Every assigned facilitator must be an active user in this organization.');if((record.sponsorOrganizationIds||[]).some(id=>!organizations.some(o=>o.id===id)))throw new Error('Select a valid co-funding organization.');const row={...record,id:id('program')};programs.unshift(row);return row;}),
 updateProgram:(user:User,programId:string,patch:Partial<Program>)=>endpoint(()=>{const i=programs.findIndex(p=>p.id===programId);if(i<0)throw new Error('Program not found.');authorize(user,'edit','programs',programs[i].organizationId,{assigned:programAssigned(user,programs[i].id),coFunded:programs[i].sponsorOrganizationIds?.includes(user.organizationId||'')});if(patch.organizationId&&patch.organizationId!==programs[i].organizationId)throw new Error('Programs cannot be moved across organizations.');const next={...programs[i],...patch,organizationId:programs[i].organizationId};programSchema.parse(next);if(next.facilitatorIds.some(fid=>!users.some(u=>u.id===fid&&u.organizationId===next.organizationId&&can(u,'view','cohorts',{organizationId:next.organizationId,resourceOrganizationId:next.organizationId,assigned:true}))))throw new Error('Every assigned facilitator must be active in this organization.');if((next.sponsorOrganizationIds||[]).some(sid=>!organizations.some(o=>o.id===sid)))throw new Error('Choose valid co-funding organizations.');programs[i]=next;return programs[i];}),
 createCohort:(user:User,record:Omit<Cohort,'id'> & {facilitatorId?:string})=>endpoint(()=>{cohortSchema.parse(record);authorize(user,'create','cohorts',record.organizationId);const program=programs.find(p=>p.id===record.programId);if(!program||program.organizationId!==record.organizationId)throw new Error('Choose a program from the same organization.');if(record.endDate<record.startDate)throw new Error('Cohort end date must be after its start date.');if(record.facilitatorId&&!users.some(u=>u.id===record.facilitatorId&&u.organizationId===record.organizationId&&can(u,'view','cohorts',{organizationId:record.organizationId,resourceOrganizationId:record.organizationId,assigned:true})))throw new Error('Choose an active facilitator in this organization.');if(record.venueId&&!venues.some(v=>v.id===record.venueId&&v.organizationId===record.organizationId))throw new Error('Choose a venue in this organization.');if(!Number.isInteger(record.capacity)||record.capacity<1)throw new Error('Cohort capacity must be a positive whole number.');const cohortId=id('cohort'),facilitatorId=record.facilitatorId;const start=`${record.startDate}T09:00:00+03:00`,end=`${record.startDate}T16:00:00+03:00`;if(facilitatorId&&sessions.some(s=>s.organizationId===record.organizationId&&new Date(s.startsAt).getTime()<new Date(end).getTime()&&new Date(s.endsAt).getTime()>new Date(start).getTime()&&(s.facilitatorIds.includes(facilitatorId)||s.venueId===record.venueId)))throw new Error('Schedule conflict: the facilitator or venue is already booked on the cohort start date.');const {facilitatorId:_assigned,...cohortData}=record;const row={...cohortData,id:cohortId};cohorts.unshift(row);if(facilitatorId){if(!program.facilitatorIds.includes(facilitatorId))program.facilitatorIds.push(facilitatorId);sessions.push({id:id('session'),organizationId:record.organizationId,cohortId,title:'Program kickoff',startsAt:start,endsAt:end,facilitatorIds:[facilitatorId],venueId:record.venueId});}return row;}),
 curriculum:(user:User,programId:string)=>endpoint(()=>visible(curriculumModules,user).filter(m=>m.programId===programId)),
 saveModule:(user:User,record:Omit<(typeof curriculumModules)[number],'id'> & {id?:string})=>endpoint(()=>{authorize(user,'edit','programs',record.organizationId,{assigned:programAssigned(user,record.programId)});if(record.id){const i=curriculumModules.findIndex(m=>m.id===record.id);if(i<0)throw new Error('Module not found.');curriculumModules[i]={...curriculumModules[i],...record};return curriculumModules[i];}const row={...record,id:id('module')};curriculumModules.push(row);return row;}),
 deleteModule:(user:User,moduleId:string)=>endpoint(()=>{const i=curriculumModules.findIndex(m=>m.id===moduleId);if(i<0)throw new Error('Module not found.');authorize(user,'edit','programs',curriculumModules[i].organizationId,{assigned:programAssigned(user,curriculumModules[i].programId)});return curriculumModules.splice(i,1)[0];}),
 issueCertificate:(user:User,programId:string,participantId:string)=>endpoint(()=>{const program=programs.find(p=>p.id===programId),person=participants.find(p=>p.id===participantId);if(!program||!person)throw new Error('Select a valid program and learner.');authorize(user,'create','certificates',program.organizationId);const eligible=enrollments.some(e=>e.programId===programId&&e.participantId===participantId&&e.status==='completed')||assessments.some(a=>a.programId===programId&&a.participantId===participantId&&a.passed);if(!eligible)throw new Error('Certificate eligibility requires program completion or a passing assessment.');const existing=certificates.find(c=>c.programId===programId&&c.participantId===participantId&&c.status==='valid');if(existing)return existing;const row={id:id('certificate'),organizationId:program.organizationId,programId,participantId,issuedAt:new Date().toISOString().slice(0,10),verificationCode:`WG-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`,publicSlug:id('verify'),status:'valid' as const};certificates.unshift(row);return row;}),
 updateNotification:(user:User,notificationId:string,read:boolean)=>endpoint(()=>{const row=appNotifications.find(n=>n.id===notificationId&&n.userId===user.id) as (typeof appNotifications)[number]|undefined;if(!row)throw new Error('Notification not found for this account.');row.readAt=read?new Date().toISOString():undefined;return row;}),
 registerForCourse:(programId:string,cohortId:string,details:{name:string;email:string})=>endpoint(()=>{const program=programs.find(p=>p.id===programId&&p.public),cohort=cohorts.find(c=>c.id===cohortId&&c.programId===programId);if(!program||!cohort)throw new Error('This course or cohort is not open for registration.');if(cohort.status==='completed')throw new Error('This cohort has already completed.');let person=participants.find(p=>p.email.toLowerCase()===details.email.toLowerCase()&&p.organizationId===program.organizationId);if(!person){person={id:id('participant'),organizationId:program.organizationId,name:details.name,email:details.email,status:'active'};participants.push(person);}if(!users.some(u=>u.email.toLowerCase()===person!.email.toLowerCase()))users.push({id:person.id,name:person.name,email:person.email,passwordHash:'mock-sha256:wego-demo',organizationId:person.organizationId,roleIds:['participant'],avatarUrl:'',status:'active'});if(enrollments.some(e=>e.cohortId===cohortId&&e.participantId===person!.id))throw new Error('You are already registered for this cohort.');const count=enrollments.filter(e=>e.cohortId===cohortId&&e.status!=='waitlisted').length;const status=count>=cohort.capacity?'waitlisted' as const:'enrolled' as const;enrollments.push({id:id('enrollment'),organizationId:program.organizationId,programId,cohortId,participantId:person.id,status,enrolledAt:new Date().toISOString().slice(0,10)});return{status,participantName:person.name,programTitle:program.title,cohortName:cohort.name};}),
 registerEvent:(eventSlug:string,details:{participantId?:string;name:string;email:string})=>endpoint(()=>{const event=events.find(e=>e.publicSlug===eventSlug&&e.public);if(!event)throw new Error('This public event is no longer available.');const registrations=eventRegistrations.filter(r=>r.eventId===event.id);if(event.capacity&&registrations.length>=event.capacity)throw new Error('This event is fully booked.');if(registrations.some(r=>r.email.toLowerCase()===details.email.toLowerCase()))throw new Error('This email is already registered for the event.');const row={id:id('registration'),organizationId:event.organizationId,eventId:event.id,participantId:details.participantId||'',name:details.name,email:details.email,registeredAt:new Date().toISOString()};eventRegistrations.push(row);return row;}),
 createParticipant:(user:User,record:Omit<(typeof participants)[number],'id'>)=>endpoint(()=>{authorize(user,'create','participants',record.organizationId);const row={...record,id:id('participant')};participants.unshift(row);return row;}),
 createEnrollment:(user:User,record:Omit<(typeof enrollments)[number],'id'>)=>endpoint(()=>{authorize(user,'create','participants',record.organizationId,{self:record.participantId===user.id});if(enrollments.some(e=>e.participantId===record.participantId&&e.cohortId===record.cohortId))throw new Error('Participant already enrolled in this cohort.');const cohort=cohorts.find(c=>c.id===record.cohortId),participant=participants.find(p=>p.id===record.participantId);if(!cohort||cohort.programId!==record.programId)throw new Error('Choose a valid cohort for this program.');if(!participant||participant.organizationId!==record.organizationId||cohort.organizationId!==record.organizationId)throw new Error('Participant, cohort, and organization must match.');const occupied=enrollments.filter(e=>e.cohortId===cohort.id&&e.status!=='waitlisted').length;const row={...record,id:id('enrollment'),status:occupied>=cohort.capacity?'waitlisted' as const:record.status};enrollments.unshift(row);return row;}),
 importParticipants:(user:User,cohortId:string,records:Array<{name:string;email:string}>)=>endpoint(()=>{const cohort=cohorts.find(c=>c.id===cohortId);if(!cohort)throw new Error('Cohort not found.');authorize(user,'create','participants',cohort.organizationId);const current=enrollments.filter(e=>e.cohortId===cohortId).length;if(records.length+current>cohort.capacity)throw new Error(`Cohort capacity exceeded. ${cohort.capacity-current} places remain.`);const emails=new Set(participants.map(p=>p.email.toLowerCase()));const valid=records.filter(r=>r.name&&/^\S+@\S+\.\S+$/.test(r.email)&&!emails.has(r.email.toLowerCase()));const created=valid.map(r=>({id:id('participant'),organizationId:cohort.organizationId,name:r.name,email:r.email,status:'active' as const}));participants.unshift(...created);enrollments.unshift(...created.map(p=>({id:id('enrollment'),organizationId:cohort.organizationId,programId:cohort.programId,cohortId,participantId:p.id,status:'enrolled' as const,enrolledAt:new Date().toISOString().slice(0,10)})));return{created:created.length,skipped:records.length-created.length};}),
 createExpense:(user:User,record:Omit<Expense,'id'>)=>endpoint(()=>{expenseSchema.parse(record);const program=programs.find(p=>p.id===record.programId);if(!program||program.organizationId!==record.organizationId)throw new Error('Expense must link to a program in the same organization.');if(!Number.isFinite(record.amountMinor)||record.amountMinor<=0)throw new Error('Expense amount must be greater than zero.');if(record.category==='per_diem'&&(!record.participantId||!record.cohortId))throw new Error('Per diem expenses require a participant and cohort.');if(record.category==='trainer_fee'&&!record.facilitatorId)throw new Error('Trainer fees must be linked to a facilitator.');if(record.category==='venue'&&!record.venueId)throw new Error('Venue costs must be linked to a venue.');authorize(user,'create','expenses',record.organizationId,{coFunded:program.sponsorOrganizationIds?.includes(user.organizationId||'')});const row={...record,id:id('expense')};expenses.unshift(row);return row;}),
 updateExpenseStatus:(user:User,expenseId:string,status:Expense['status'])=>endpoint(()=>{const row=expenses.find(e=>e.id===expenseId);if(!row)throw new Error('Expense not found.');authorize(user,'approve','expenses',row.organizationId,{coFunded:programs.find(p=>p.id===row.programId)?.sponsorOrganizationIds?.includes(user.organizationId||'')});row.status=status;return row;}),
 recordAttendance:(user:User,record:typeof attendance[number])=>endpoint(()=>{const session=sessions.find(s=>s.id===record.sessionId),person=participants.find(p=>p.id===record.participantId);if(!session||session.organizationId!==record.organizationId||!person||person.organizationId!==record.organizationId||!enrollments.some(e=>e.cohortId===session.cohortId&&e.participantId===person.id))throw new Error('Attendance must match an enrolled learner and session in the same organization.');authorize(user,'create','attendance',record.organizationId,{self:record.participantId===user.id,assigned:!!session.facilitatorIds.includes(user.id)});const index=attendance.findIndex(r=>r.id===record.id);if(index<0)attendance.push(record);else attendance[index]=record;return record;}),
 updateAttendance:(user:User,attendanceId:string,state:typeof attendance[number]['state'])=>endpoint(()=>{const row=attendance.find(a=>a.id===attendanceId);if(!row)throw new Error('Attendance record not found.');const session=sessions.find(s=>s.id===row.sessionId);authorize(user,'edit','attendance',row.organizationId,{assigned:!!session?.facilitatorIds.includes(user.id),self:row.participantId===user.id});row.state=state;return row;}),
 submitAssessment:(user:User,record:{programId:string;cohortId:string;participantId:string;score:number;maxScore:number;title?:string})=>endpoint(()=>{const program=programs.find(p=>p.id===record.programId),participant=participants.find(p=>p.id===record.participantId);if(!program||!participant||participant.organizationId!==program.organizationId)throw new Error('Assessment program and learner must belong to the same organization.');authorize(user,'create','assessments',program.organizationId,{self:record.participantId===user.id,assigned:programAssigned(user,program.id)});if(record.score<0||record.score>record.maxScore||record.maxScore<=0)throw new Error('Score must be between zero and the assessment maximum.');if(record.participantId===user.id&&!enrollments.some(e=>e.participantId===user.id&&e.programId===program.id))throw new Error('You must be enrolled in this program to submit an assessment.');const row={id:id('assessment'),organizationId:program.organizationId,programId:program.id,cohortId:record.cohortId,participantId:record.participantId,title:record.title||'Applied learning assessment',score:record.score,maxScore:record.maxScore,passed:record.score/record.maxScore>=0.7,assessedAt:new Date().toISOString().slice(0,10)};assessments.unshift(row);return row;}),
 submitEvaluation:(user:User,record:{programId:string;cohortId:string;participantId:string;rating:number;responses:{relevance:string;facilitation:string}})=>endpoint(()=>{const program=programs.find(p=>p.id===record.programId),participant=participants.find(p=>p.id===record.participantId),cohort=cohorts.find(c=>c.id===record.cohortId);if(!program||!participant||participant.organizationId!==program.organizationId||!cohort||cohort.organizationId!==program.organizationId||cohort.programId!==program.id)throw new Error('Evaluation must reference a learner, program, and cohort in the same organization.');authorize(user,'create','evaluations',program.organizationId,{self:record.participantId===user.id,assigned:programAssigned(user,program.id)});if(record.participantId===user.id&&!enrollments.some(e=>e.participantId===user.id&&e.cohortId===cohort.id))throw new Error('You must be enrolled in this course to submit an evaluation.');if(record.rating<1||record.rating>5)throw new Error('Evaluation rating must be between one and five.');const row={id:id('evaluation'),organizationId:program.organizationId,programId:program.id,cohortId:record.cohortId,participantId:record.participantId,rating:record.rating,responses:record.responses,submittedAt:new Date().toISOString()};evaluations.unshift(row);return row;}),
 qrCheckIn:(user:User,sessionId:string)=>endpoint(()=>{const session=sessions.find(s=>s.id===sessionId);if(!session)throw new Error('Session not found.');assertTenant(user,session.organizationId);if(!can(user,'create','attendance',{self:true,organizationId:user.organizationId||undefined,resourceOrganizationId:session.organizationId}))throw new Error('Your account cannot self check in.');const participant=participants.find(p=>p.id===user.id&&p.organizationId===session.organizationId);if(!participant)throw new Error('No participant record is linked to this account.');if(!enrollments.some(e=>e.cohortId===session.cohortId&&e.participantId===participant.id))throw new Error('You are not enrolled in this cohort.');let row=attendance.find(a=>a.sessionId===sessionId&&a.participantId===participant.id);if(row){row.state='present';return row;}row={id:id('attendance'),organizationId:session.organizationId,sessionId,participantId:participant.id,state:'present'};attendance.push(row);return row;}),
 saveBlogPost:(user:User,record:Partial<(typeof blogPosts)[number]> & Pick<(typeof blogPosts)[number],'organizationId'|'title'|'body'>)=>endpoint(()=>{blogSchema.parse({organizationId:record.organizationId,title:record.title,body:record.body,tags:record.tags||[]});const previous=record.id?blogPosts.find(p=>p.id===record.id):undefined;const action:Action=!record.id?'create':record.status==='published'&&previous?.status!=='published'?'publish':'edit';authorize(user,action,'blog',record.organizationId,{assigned:!!record.programId&&programAssigned(user,record.programId)});if(!record.id&&record.status==='published')authorize(user,'publish','blog',record.organizationId,{assigned:!!record.programId&&programAssigned(user,record.programId)});if(record.id){const i=blogPosts.findIndex(p=>p.id===record.id);if(i<0)throw new Error('Story not found.');blogPosts[i]={...blogPosts[i],...record,body:DOMPurify.sanitize(record.body)};return blogPosts[i];}const row={id:id('story'),programId:'',cohortId:'',coverImageUrl:'',galleryUrls:[],authorId:user.id,status:'draft' as const,publishedAt:'',tags:[],publicSlug:id('story'),...record,body:DOMPurify.sanitize(record.body)};blogPosts.unshift(row);return row;}),
 saveEvent:(user:User,record:Partial<(typeof events)[number]> & Pick<(typeof events)[number],'organizationId'|'title'|'description'|'startsAt'|'endsAt'>)=>endpoint(()=>{contentSchema.parse({organizationId:record.organizationId,title:record.title,description:record.description,startsAt:record.startsAt,endsAt:record.endsAt,capacity:record.capacity});const previous=record.id?events.find(e=>e.id===record.id):undefined;const action:Action=!record.id?'create':record.public&&!previous?.public?'publish':'edit';authorize(user,action,'events',record.organizationId);if(!record.id&&record.public)authorize(user,'publish','events',record.organizationId);if(record.id){const i=events.findIndex(e=>e.id===record.id);if(i<0)throw new Error('Event not found.');events[i]={...events[i],...record};return events[i];}const row={id:id('event'),programId:'',cohortId:'',imageUrl:'',venueId:'',registrationUrl:'',capacity:50,status:'upcoming' as const,public:true,publicSlug:id('event'),...record};events.unshift(row);return row;}),
 createRole:(user:User,record:{id?:string;name:string;description:string;scope:'organization';organizationId:string;permissions:Array<{resource:Resource;action:Action;scope:'organization'|'assigned'|'self'}>})=>endpoint(()=>{authorize(user,'manage','users',record.organizationId);const role={id:record.id||id('role'),name:record.name,description:record.description,scope:'organization' as const,organizationId:record.organizationId,builtIn:false};roles.push(role);record.permissions.forEach(g=>permissionGrants.push({roleId:role.id,...g}));return role;}),
 inviteUser:(user:User,record:{name:string;email:string;roleIds:string[];organizationId?:string})=>endpoint(()=>{const organizationId=record.organizationId||user.organizationId;if(!organizationId)throw new Error('Select an organization before adding a user.');userInviteSchema.parse({...record,organizationId});authorize(user,'create','users',organizationId);if(users.some(u=>u.email.toLowerCase()===record.email.toLowerCase()))throw new Error('This email already has a WeGo.org account.');if(!record.roleIds.length||record.roleIds.some(rid=>{const role=roles.find(r=>r.id===rid);return !role||role.scope==='platform'||role.organizationId&&role.organizationId!==organizationId}))throw new Error('Choose a valid role available to this organization.');const row={id:id('user'),name:record.name,email:record.email,passwordHash:'mock-sha256:wego-demo',organizationId,roleIds:record.roleIds,avatarUrl:'',status:'active' as const};users.unshift(row);return{...row,passwordHash:undefined};}),
 onboardOrganization:(user:User,record:Omit<(typeof organizations)[number],'id'|'slug'> & {adminName:string;adminEmail:string})=>endpoint(()=>{authorize(user,'manage','organizations',user.organizationId||'__platform__');if(users.some(u=>u.email.toLowerCase()===record.adminEmail.toLowerCase()))throw new Error('The initial administrator email is already registered.');const {adminName,adminEmail,...orgData}=record;const row={...orgData,id:id('org'),slug:id('tenant')};organizations.push(row);users.push({id:id('user'),name:adminName,email:adminEmail,passwordHash:'mock-sha256:wego-demo',organizationId:row.id,roleIds:['org-admin'],avatarUrl:'',status:'active'});return row;}),
 updateOrganization:(user:User,organizationId:string,patch:Partial<(typeof organizations)[number]>)=>endpoint(()=>{authorize(user,'edit','organizations',organizationId);const row=organizations.find(o=>o.id===organizationId);if(!row)throw new Error('Organization not found.');Object.assign(row,patch);return row;}),
 revokeCertificate:(user:User,certificateId:string)=>endpoint(()=>{const row=certificates.find(c=>c.id===certificateId);if(!row)throw new Error('Certificate not found.');authorize(user,'edit','certificates',row.organizationId);row.status='revoked';return row;}),
 publicCatalog:()=>endpoint(()=>programs.filter(p=>p.public).map(({id,organizationId,title,description,category,sectorTags,cpdCredits,durationHours,deliveryMode})=>({id,organizationId,title,description,category,sectorTags,cpdCredits,durationHours,deliveryMode}))),
 publicEvents:()=>endpoint(()=>events.filter(e=>e.public&&e.status==='upcoming')),
 publicStories:()=>endpoint(()=>blogPosts.filter(p=>p.status==='published')),
 publicCertificate:(slug:string)=>endpoint(()=>{const c=certificates.find(x=>x.publicSlug===slug&&x.status==='valid');if(!c)return null;const person=participants.find(p=>p.id===c.participantId),program=programs.find(p=>p.id===c.programId);return{verificationCode:c.verificationCode,issuedAt:c.issuedAt,recipient:person?.name,program:program?.title,status:c.status};}),
};
export const mockReferenceData={permissionGrants};
