import { organizations, programs, cohorts, users } from './seed';
export interface BlogPost { id: string; organizationId: string; programId: string; cohortId: string; title: string; body: string; coverImageUrl: string; galleryUrls: string[]; authorId: string; status: 'draft'|'published'; publishedAt: string; tags: string[]; publicSlug: string; }
export interface PublicEvent { id: string; organizationId: string; programId: string; cohortId: string; title: string; description: string; imageUrl: string; startsAt: string; endsAt: string; venueId: string; registrationUrl: string; capacity: number; status: 'upcoming'|'completed'; public: boolean; publicSlug: string; }
const storyTitles = ['Learning that travels further','A new chapter in public service learning','Building opportunity, one skill at a time','From classroom to community impact','The next generation of digital leaders','Partnerships that power progress'];
export const blogPosts: BlogPost[] = storyTitles.map((title,i)=>{const org=organizations[i%3], program=programs.find(p=>p.organizationId===org.id)!;return {id:`story-${i+1}`,organizationId:org.id,programId:program.id,cohortId:cohorts.find(c=>c.programId===program.id)!.id,title,body:`${title}. Local expertise, thoughtful training, and shared purpose come together in a practical learning journey. Participants translate new knowledge into action rooted in their own context.`,coverImageUrl:'',galleryUrls:[],authorId:users.find(u=>u.organizationId===org.id)?.id||'u-super',status:i===0||i===2||i===4?'published':'draft',publishedAt:`2026-0${(i%8)+1}-12`,tags:[org.type,'outcomes','learning'],publicSlug:`story-${i+1}`};});
export const events: PublicEvent[] = Array.from({length:6},(_,i)=>{const org=organizations[i%3],program=programs.find(p=>p.organizationId===org.id)!,day=new Date(i<3?Date.UTC(2026,9,22+i*4):Date.UTC(2026,5+i-3,10)).toISOString().slice(0,10);return {id:`event-${i+1}`,organizationId:org.id,programId:program.id,cohortId:cohorts.find(c=>c.programId===program.id)!.id,title:['Skills for a changing future','Public service learning forum','Designing for inclusive growth','Digital skills showcase','Learning leaders roundtable','Workforce innovation day'][i],description:'A focused, practical learning experience bringing together practitioners and institutions.',imageUrl:'',startsAt:`${day}T09:00:00+03:00`,endsAt:`${day}T16:00:00+03:00`,venueId:`venue-${i%3+1}`,registrationUrl:`/events/wego-learning-${i+1}`,capacity:80,status:i===0||i===1||i===2?'upcoming':'completed',public:true,publicSlug:`wego-learning-${i+1}`};});
export const facilitatorProfiles=users.filter(u=>u.roleIds.includes('facilitator')).map((u,i)=>({id:`facilitator-profile-${i+1}`,organizationId:u.organizationId!,userId:u.id,bio:'Experienced practitioner and learning facilitator with a strong track record in adult learning.',expertiseTags:[['Leadership','Program design','Digital skills','Compliance'][i%4],'Facilitation','Training of trainers'],qualifications:['Certified Learning Professional','Adult Education Diploma'],availability:'available'}));
export const venues=organizations.map((org,i)=>({id:`venue-${i+1}`,organizationId:org.id,name:['Innovation Hub Addis','National Training Centre','Vertex Learning Studio'][i],address:'Addis Ababa, Ethiopia',capacity:100,virtual:false,notes:'Accessible training venue with hybrid meeting facilities.'}));
export const enrollments=Array.from({length:120},(_,i)=>({id:`enroll-${i+1}`,organizationId:organizations[i%3].id,programId:programs[i%programs.length].id,cohortId:cohorts[i%cohorts.length].id,participantId:i===0?'u-trainee':`participant-${String(i+1).padStart(3,'0')}`,status:(i%4===0?'completed':i%9===0?'waitlisted':'enrolled') as 'completed'|'waitlisted'|'enrolled',enrolledAt:`2026-0${i%8+1}-03`}));
export const assessments=Array.from({length:72},(_,i)=>({id:`assessment-${i+1}`,organizationId:organizations[i%3].id,programId:programs[i%programs.length].id,cohortId:cohorts[i%cohorts.length].id,participantId:`participant-${String(i+1).padStart(3,'0')}`,title:'Applied learning assessment',score:65+(i*7)%36,maxScore:100,passed:(i*7)%36>=10,assessedAt:`2026-05-${String(i%27+1).padStart(2,'0')}`}));
export const evaluations=Array.from({length:45},(_,i)=>({id:`evaluation-${i+1}`,organizationId:organizations[i%3].id,programId:programs[i%programs.length].id,cohortId:cohorts[i%cohorts.length].id,participantId:`participant-${String(i+1).padStart(3,'0')}`,rating:3+(i%3),responses:{relevance:'high',facilitation:'excellent'},submittedAt:`2026-06-${String(i%27+1).padStart(2,'0')}`}));
export const eventRegistrations:Array<{id:string;organizationId:string;eventId:string;participantId:string;name:string;email:string;registeredAt:string}> = [];
export interface DemoNotification{id:string;organizationId:string;userId:string;type:string;title:string;body:string;createdAt:string;readAt?:string;}
export const appNotifications:DemoNotification[]=users.filter(u=>u.organizationId).flatMap((u,i)=>[
 {id:`notification-${i}-1`,organizationId:u.organizationId!,userId:u.id,type:'enrollment',title:'New participants enrolled',body:'Learners were added to an upcoming cohort.',createdAt:'2026-09-28T10:00:00+03:00',readAt:undefined},
 {id:`notification-${i}-2`,organizationId:u.organizationId!,userId:u.id,type:'session',title:'Session reminder',body:'A learning session is coming up tomorrow.',createdAt:'2026-09-27T14:00:00+03:00',readAt:undefined}
]);
