// Deterministic demo names generated with @faker-js/faker. Rebuild with scripts/generate-mock-names.mjs.
export const generatedNames = [
  "Armani Moen",
  "Eldridge Bruen",
  "Haven Pouros",
  "Cleora Abernathy",
  "Raegan Kuhic MD",
  "Alfred Conn DDS",
  "Mr. Kip McDermott",
  "Lorna Brekke",
  "Aurelie Casper-Grant",
  "Nyah Runte",
  "Maddison Orn",
  "Homer Durgan II",
  "Mrs. Elna Swaniawski",
  "Lew Kulas",
  "Emmanuelle Reichert",
  "Justine Tillman",
  "Tito Cummings",
  "Stephan Mante",
  "Paris Considine DDS",
  "Mr. Erich Mayer",
  "Kaitlyn Harvey",
  "Emil Hoeger",
  "Cary Fadel",
  "Jacey Durgan Jr.",
  "Angela Okuneva",
  "Roy Hammes",
  "Orrin Auer",
  "Nestor Towne MD",
  "Daryl Conroy",
  "Noemy Kuhic",
  "Roslyn Ward",
  "Jaylan Hoppe",
  "Dexter Ward",
  "Amanda Von",
  "Freda Jacobson",
  "Jaida Hahn-Welch",
  "Loma Barrows",
  "Orrin Fay",
  "Tiffany Jacobi-Bayer",
  "Domenic Bayer",
  "Stephon Littel",
  "Alfonso Von",
  "Dayne Kub",
  "Dakota Lesch",
  "Unique Bergnaum",
  "Lana Fisher",
  "Ms. Arianna Nitzsche",
  "Demetris Heathcote",
  "Friedrich Watsica",
  "Mariana Bernier",
  "Dr. Alanis VonRueden",
  "Zechariah Jaskolski",
  "Darby Shanahan",
  "Zander Rippin",
  "Jeannie Berge",
  "Gonzalo Harris-Ernser",
  "Dax Stroman",
  "Winona Tromp",
  "Mrs. Katharina Feeney",
  "Adrienne Klocko",
  "Milan Rau",
  "Jaylon Cassin",
  "Yvonne Marvin",
  "Geneva Spencer",
  "Mr. Burdette Hammes",
  "Judge Pollich",
  "Hayden Cremin",
  "Brown Schumm",
  "Cletus Kreiger",
  "Cali Brown",
  "Herta Abernathy",
  "Jack Towne",
  "Brown Hilpert",
  "Kimberly Heller",
  "Lambert Runolfsson",
  "Ciara Ankunding",
  "Francisca Conn",
  "Watson Stoltenberg",
  "Devante Mertz",
  "Kristy Streich",
  "Ona Schaden",
  "Leonor Heller",
  "Eleonore Kemmer",
  "Arden Bode",
  "Mr. Lowell Bednar",
  "Betsy McCullough",
  "Zachary McDermott",
  "Mrs. Roberta Lindgren III",
  "Brody Muller",
  "Kolby Beatty",
  "Amir Pollich",
  "Coleman Predovic",
  "Lolita Donnelly",
  "Mr. Colten Glover",
  "Nathen Ruecker-Stracke",
  "Helga Bauch",
  "Bryon Sipes",
  "Mable Lemke",
  "Joseph Reichert-Deckow",
  "Muhammad Murphy",
  "Nia Rau-Osinski PhD",
  "Wade Prohaska IV",
  "Taylor Runolfsdottir",
  "Mr. Rigoberto Kreiger",
  "Jan Hartmann",
  "Ms. Abigale Kertzmann",
  "Aimee Monahan",
  "Dayne Hahn-Lemke",
  "Osborne Moore",
  "Lucius Boyle",
  "Dr. Vincenza Dare",
  "Blanche Fadel",
  "Anahi Klocko",
  "Mr. Giovanny Dach",
  "Queenie Legros",
  "Nelda Boyer DDS",
  "Martine Franey",
  "Scot McCullough",
  "Helmer Monahan",
  "Zora Balistreri-Hartmann",
  "Alexanne Morissette",
  "Mark Ferry",
  "Deondre Klein",
  "Nona King",
  "Alek Wilderman",
  "Maximillia Prohaska",
  "Rebeka Gorczany",
  "Aliya Dach",
  "Rickey Mosciski",
  "Edyth Trantow",
  "Alexandre Schneider",
  "Ursula Crona"
] as const;
