export type OrgType = 'ngo' | 'government' | 'private';
export type Action = 'view' | 'create' | 'edit' | 'delete' | 'approve' | 'export' | 'publish' | 'manage';
export type Resource = 'organizations' | 'users' | 'programs' | 'cohorts' | 'participants' | 'attendance' | 'expenses' | 'reports' | 'blog' | 'events' | 'certificates' | 'notifications' | 'assessments' | 'evaluations' | 'venues' | 'curriculum';
export type Scope = 'platform' | 'organization' | 'assigned' | 'self' | 'co-funded' | 'public';
export interface Organization { id: string; name: string; slug: string; type: OrgType; description: string; logoUrl: string; brand: { primaryColor: string; accentColor: string }; country: string; timezone: string; currency: string; status: 'active' | 'onboarding'; }
export interface User { id: string; name: string; email: string; passwordHash: string; organizationId: string | null; roleIds: string[]; avatarUrl: string; status: 'active' | 'invited' | 'suspended'; }
export interface Role { id: string; name: string; description: string; scope: Scope; organizationId: string | null; builtIn: boolean; }
export interface PermissionGrant { roleId: string; resource: Resource; action: Action; scope: Scope; }
export interface Program { id: string; organizationId: string; title: string; description: string; category: string; sectorTags: string[]; cpdCredits: number; durationHours: number; deliveryMode: 'in_person' | 'online' | 'hybrid'; status: 'planning' | 'active' | 'completed'; public: boolean; budgetAmountMinor: number; currency: string; facilitatorIds: string[]; sponsorOrganizationIds?:string[]; }
export interface Cohort { id: string; organizationId: string; programId: string; name: string; startDate: string; endDate: string; capacity: number; status: 'upcoming' | 'ongoing' | 'completed'; venueId?: string; }
export interface Participant { id: string; organizationId: string; name: string; email: string; status: 'active' | 'completed'; }
export interface Expense { id: string; organizationId: string; programId: string; cohortId?: string; sessionId?: string; participantId?: string; facilitatorId?: string; venueId?: string; category: 'per_diem' | 'trainer_fee' | 'venue' | 'logistics' | 'catering' | 'stationery_equipment'; description: string; amountMinor: number; currency: string; status: 'planned' | 'approved' | 'paid'; incurredAt?: string; dueAt?: string; paymentMethod?: string; quantity?: number; unitRateMinor?: number; daysAttended?: number; }
export interface Session { id: string; organizationId: string; cohortId: string; title: string; startsAt: string; endsAt: string; facilitatorIds: string[]; venueId?:string; objectives?:string[]; materials?:string[]; }
export interface Attendance { id: string; organizationId: string; sessionId: string; participantId: string; state: 'present' | 'late' | 'absent' | 'excused'; }
export interface Certificate { id: string; organizationId: string; programId: string; participantId: string; issuedAt: string; verificationCode: string; publicSlug: string; status: 'valid' | 'revoked'; }
export interface CurriculumModule { id:string; organizationId:string; programId:string; title:string; description:string; sequence:number; objectives:string[]; materials:string[]; }
export interface Assessment { id:string; organizationId:string; programId:string; cohortId:string; participantId:string; title:string; score:number; maxScore:number; passed:boolean; assessedAt:string; }
export interface EvaluationResponse { id:string; organizationId:string; programId:string; cohortId:string; participantId:string; rating:number; responses:Record<string,string>; submittedAt:string; }
export interface AppNotification { id:string; organizationId:string; userId:string; type:string; title:string; body:string; createdAt:string; readAt?:string; relatedEntityType?:string; relatedEntityId?:string; }
