import {useState} from 'react';
import {flexRender,getCoreRowModel,getFilteredRowModel,getPaginationRowModel,getSortedRowModel,useReactTable,type ColumnDef,type RowSelectionState,type VisibilityState,type Updater} from '@tanstack/react-table';
import {ArrowDown,ArrowUp,ChevronLeft,ChevronRight,ChevronsUpDown,Search} from 'lucide-react';
type Props<T>={data:T[];columns:ColumnDef<T,any>[];getRowId:(row:T)=>string;globalFilter:string;onGlobalFilterChange:(value:string)=>void;rowSelection:RowSelectionState;onRowSelectionChange:(updater:Updater<RowSelectionState>)=>void;columnVisibility?:VisibilityState;onColumnVisibilityChange?:(updater:Updater<VisibilityState>)=>void;emptyMessage?:string;pageSizes?:number[]};
export function DataTable<T>({data,columns,getRowId,globalFilter,onGlobalFilterChange,rowSelection,onRowSelectionChange,columnVisibility,onColumnVisibilityChange,emptyMessage='No records match these filters.',pageSizes=[10,25,50]}:Props<T>){
 const [pageSize,setPageSize]=useState(pageSizes[0]||10);
 const table=useReactTable({data,columns,getRowId,state:{globalFilter,rowSelection,columnVisibility},onColumnVisibilityChange,onGlobalFilterChange:value=>onGlobalFilterChange(String(value??'')),onRowSelectionChange,enableRowSelection:true,getCoreRowModel:getCoreRowModel(),getFilteredRowModel:getFilteredRowModel(),getSortedRowModel:getSortedRowModel(),getPaginationRowModel:getPaginationRowModel(),initialState:{pagination:{pageSize}}});
 const pages=table.getPageCount();
 return <section className="data-table-component"><div className="data-table-tools"><label className="search-field data-table-search"><Search size={15}/><input aria-label="Search table" placeholder="Search visible records" value={globalFilter} onChange={e=>onGlobalFilterChange(e.target.value)}/>{globalFilter&&<button type="button" aria-label="Clear search" onClick={()=>onGlobalFilterChange('')}>×</button>}</label><label className="table-page-size">Rows<select value={pageSize} onChange={e=>{const n=Number(e.target.value);setPageSize(n);table.setPageSize(n)}}>{pageSizes.map(n=><option value={n} key={n}>{n}</option>)}</select></label></div><div className="table-scroll data-table-scroll"><table className="data-table"><thead>{table.getHeaderGroups().map(group=><tr key={group.id}>{group.headers.map(header=><th key={header.id} style={{width:header.getSize()===150?undefined:header.getSize()}}>{header.isPlaceholder?null:header.column.getCanSort()?<button type="button" className="data-table-sort" onClick={header.column.getToggleSortingHandler()}>{flexRender(header.column.columnDef.header,header.getContext())}{header.column.getIsSorted()==='asc'?<ArrowUp size={12}/>:header.column.getIsSorted()==='desc'?<ArrowDown size={12}/>:<ChevronsUpDown size={12}/>}</button>:flexRender(header.column.columnDef.header,header.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(row=><tr key={row.id} data-selected={row.getIsSelected()||undefined}>{row.getVisibleCells().map(cell=><td key={cell.id}>{flexRender(cell.column.columnDef.cell,cell.getContext())}</td>)}</tr>)}{table.getRowModel().rows.length===0&&<tr><td colSpan={table.getVisibleLeafColumns().length} className="data-table-empty">{emptyMessage}</td></tr>}</tbody></table></div><footer className="data-table-pagination"><span>{table.getFilteredRowModel().rows.length?`${table.getState().pagination.pageIndex*pageSize+1}–${Math.min((table.getState().pagination.pageIndex+1)*pageSize,table.getFilteredRowModel().rows.length)} of ${table.getFilteredRowModel().rows.length}`:'0 results'}{Object.keys(rowSelection).length>0&&` · ${Object.keys(rowSelection).length} selected`}</span><div><button type="button" className="button button-secondary" onClick={()=>table.previousPage()} disabled={!table.getCanPreviousPage()} aria-label="Previous page"><ChevronLeft size={15}/></button><span>Page {Math.min(table.getState().pagination.pageIndex+1,Math.max(1,pages))} of {Math.max(1,pages)}</span><button type="button" className="button button-secondary" onClick={()=>table.nextPage()} disabled={!table.getCanNextPage()} aria-label="Next page"><ChevronRight size={15}/></button></div></footer></section>
}
export const selectionColumn=<T,>():ColumnDef<T,unknown>=>({id:'select',header:({table})=><input aria-label="Select all rows on page" type="checkbox" checked={table.getIsAllPageRowsSelected()} ref={el=>{if(el)el.indeterminate=table.getIsSomePageRowsSelected()}} onChange={table.getToggleAllPageRowsSelectedHandler()}/>,cell:({row})=><input aria-label={`Select row ${row.id}`} type="checkbox" checked={row.getIsSelected()} disabled={!row.getCanSelect()} onChange={row.getToggleSelectedHandler()}/>,enableSorting:false,enableGlobalFilter:false,size:42});
