import {useEffect,useRef,type ButtonHTMLAttributes,type ReactNode} from 'react';
import {Check,X} from 'lucide-react';
import type {Action,PermissionGrant,Resource} from '../mock-data/types';
export function Button({children,variant='primary',loading=false,className='',...props}:{children:ReactNode;variant?:'primary'|'secondary'|'quiet'|'dark';loading?:boolean;className?:string}&ButtonHTMLAttributes<HTMLButtonElement>){return <button className={`button button-${variant} ${className}`} aria-busy={loading||undefined} {...props}>{loading?<><span className="spinner"/>Loading…</>:children}</button>}
export function Field({label,children,wide=false}:{label:string;children:ReactNode;wide?:boolean}){return <label className={`form-field ${wide?'field-wide':''}`}><span>{label}</span>{children}</label>}
export function Notice({text,tone='success'}:{text:string;tone?:'success'|'error'}){return text?<div className={`feature-notice notice-${tone}`}>{tone==='success'?<Check size={15}/>:<span>!</span>}{text}</div>:null}
export function Modal({title,sub,onClose,children}:{title:string;sub?:string;onClose:()=>void;children:ReactNode}){const dialog=useRef<HTMLElement>(null),close=useRef(onClose);close.current=onClose;useEffect(()=>{const before=document.activeElement as HTMLElement|null,old=document.body.style.overflow;document.body.style.overflow='hidden';dialog.current?.querySelector<HTMLElement>('input,select,textarea,button')?.focus();function keys(e:KeyboardEvent){if(e.key==='Escape'){close.current();return;}if(e.key==='Tab'&&dialog.current){const items=[...dialog.current.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href]')];if(!items.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}document.addEventListener('keydown',keys);return()=>{document.removeEventListener('keydown',keys);document.body.style.overflow=old;before?.focus()}},[]);return <div className="modal-scrim" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="modal" ref={dialog} role="dialog" aria-modal="true" aria-label={title}><header className="modal-head"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div><button type="button" className="modal-close" onClick={onClose} aria-label="Close dialog"><X size={18}/></button></header>{children}</section></div>}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:string}){return <span className={`badge badge-${tone}`}>{children}</span>}
const statusTone:Record<string,string>={active:'green',completed:'green',invited:'orange',suspended:'red',deactivated:'neutral',upcoming:'orange',ongoing:'green',valid:'green',revoked:'red',paid:'green',approved:'orange',planned:'neutral',published:'green',draft:'neutral',enrolled:'green',waitlisted:'orange',platform:'neutral',organization:'neutral',assigned:'orange',self:'green','co-funded':'orange',public:'green',locked:'neutral'};
export function StatusBadge({status}:{status:string}){return <Badge tone={statusTone[status]||'neutral'}>{status.replaceAll('_',' ')}</Badge>}
const matrixResources:{id:Resource;label:string}[]=[{id:'programs',label:'Programs'},{id:'cohorts',label:'Cohorts'},{id:'participants',label:'Participants'},{id:'facilitators',label:'Facilitators'},{id:'attendance',label:'Attendance'},{id:'certificates',label:'Certificates'},{id:'expenses',label:'Finance / Expenses'},{id:'blog',label:'Blog / Stories'},{id:'events',label:'Events'},{id:'reports',label:'Reports'},{id:'users',label:'Users'},{id:'person_identity',label:'Person identity fields'},{id:'person_demographics',label:'Person demographic fields'},{id:'person_financial',label:'Person financial fields'},{id:'person_emergency',label:'Emergency contact fields'},{id:'roles',label:'Roles & Permissions'},{id:'organizations',label:'Organization Settings'}];
const matrixActions:Action[]=['view','create','edit','delete','approve','export'];
export function PermissionMatrix({roleId,selected,onChange,scope,onScope,readOnly=false}:{roleId:string;selected:PermissionGrant[];onChange:(grants:PermissionGrant[])=>void;scope:PermissionGrant['scope'];onScope:(scope:PermissionGrant['scope'])=>void;readOnly?:boolean}){return <div className="permission-editor"><div className="permission-scope"><label>Scope for selected capabilities<select value={scope} disabled={readOnly} onChange={e=>onScope(e.target.value as PermissionGrant['scope'])}><option value="organization">This organization</option><option value="assigned">Assigned records</option><option value="self">Own account / records</option><option value="co-funded">Co-funded records</option><option value="public">Public resources</option><option value="platform">Platform-wide</option></select></label><span>Choose a scope, then grant access by module and action.</span></div><div className="permission-grid-scroll"><div className="role-matrix role-matrix-shared"><div className="role-matrix-row matrix-head"><b>Module</b>{matrixActions.map(action=><span key={action}>{action}</span>)}</div>{matrixResources.map(resource=><div className="role-matrix-row" key={resource.id}><b>{resource.label}</b>{matrixActions.map(action=>{const checked=selected.some(g=>g.resource===resource.id&&g.action===action);return <label key={action} aria-label={`${resource.label}: ${action}`}><input type="checkbox" checked={checked} disabled={readOnly} onChange={e=>{const rest=selected.filter(g=>g.resource!==resource.id||g.action!==action);onChange(e.target.checked?[...rest,{roleId,resource:resource.id,action,scope}]:rest)}}/></label>})}</div>)}</div></div></div>}
