import {useState} from 'react';
import {Activity,ArrowUpRight,Award,BookOpen,CalendarDays,Check,ClipboardList,CreditCard,FileText,Users,WalletCards} from 'lucide-react';
import {can,visibleFields} from '../mock-data/permissions';
import {accountActivity,assessments,blogPosts,enrollments,evaluations,events} from '../mock-data/content';
import {attendance,certificates,cohorts,expenses,organizations,programs,sessions,users} from '../mock-data/seed';
import {roles} from '../mock-data/roles';
import {derivedPersonMetrics,personPhotoAllowed} from '../mock-data/person-profile';
import type {User} from '../mock-data/types';
import {Badge,Modal,StatusBadge} from './ui';
import Share from './Share';

type Actor=Omit<User,'passwordHash'>;
const cash=(minor:number,currency='ETB')=>new Intl.NumberFormat('en-ET',{style:'currency',currency,maximumFractionDigits:0}).format(minor/100);
export function User360Profile({viewer,person,onClose}:{viewer:Actor;person:User;onClose:()=>void}){
 const [tab,setTab]=useState('overview');const orgId=person.organizationId||undefined,self=person.id===viewer.id,viewerAdmin=can(viewer,'view','users',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:orgId});
 const profileFields=visibleFields(viewer,person);const derived=derivedPersonMetrics(person);
 const personPrograms=programs.filter(p=>(p.organizationId===person.organizationId)&&(p.facilitatorIds.includes(person.id)||enrollments.some(e=>e.participantId===person.id&&e.programId===p.id)));
 const viewerOrgAttendance=can(viewer,'view','attendance',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:orgId}),viewerAssignedAttendance=can(viewer,'view','attendance',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:orgId,assigned:true});
 const targetSessions=sessions.filter(s=>s.organizationId===person.organizationId&&(s.facilitatorIds.includes(person.id)||attendance.some(a=>a.participantId===person.id&&a.sessionId===s.id)));
 const personSessions=targetSessions.filter(s=>viewerOrgAttendance||self||viewerAssignedAttendance&&s.facilitatorIds.includes(viewer.id));
 const visibleSessionIds=new Set(personSessions.map(s=>s.id));
 const personAttendance=attendance.filter(a=>visibleSessionIds.has(a.sessionId)&&(a.participantId===person.id||personSessions.some(s=>s.id===a.sessionId&&s.facilitatorIds.includes(person.id))));
 const visibleProgramRows=personPrograms.filter(p=>can(viewer,'view','programs',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:p.organizationId})||can(viewer,'view','programs',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:p.organizationId,assigned:p.facilitatorIds.includes(viewer.id),self:self&&enrollments.some(e=>e.participantId===viewer.id&&e.programId===p.id)})||p.public&&can(viewer,'view','programs',{self:true,organizationId:viewer.organizationId||undefined,resourceOrganizationId:p.organizationId}));
 const programsAllowed=visibleProgramRows.length>0;
 const viewerCanAssess=can(viewer,'view','assessments',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:orgId,self,assigned:true}),viewerCanEvaluate=can(viewer,'view','evaluations',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:orgId,self,assigned:true});
 const personAssessments=viewerCanAssess?assessments.filter(a=>{const p=visibleProgramRows.find(x=>x.id===a.programId);return !!p&&(a.participantId===person.id||p.facilitatorIds.includes(person.id))&&can(viewer,'view','assessments',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:a.organizationId,self:self&&a.participantId===viewer.id,assigned:p.facilitatorIds.includes(viewer.id)});}):[];
 const personEvaluations=viewerCanEvaluate?evaluations.filter(e=>{const p=visibleProgramRows.find(x=>x.id===e.programId);return !!p&&(e.participantId===person.id||p.facilitatorIds.includes(person.id))&&can(viewer,'view','evaluations',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:e.organizationId,self:self&&e.participantId===viewer.id,assigned:p.facilitatorIds.includes(viewer.id)});}):[];
 const personCertificates=certificates.filter(c=>c.participantId===person.id&&can(viewer,'view','certificates',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:c.organizationId,self,assigned:visibleProgramRows.some(p=>p.id===c.programId&&p.facilitatorIds.includes(viewer.id))}));
 const viewerOrgFinance=can(viewer,'view','expenses',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:orgId});
 const personExpenses=expenses.filter(e=>{const p=visibleProgramRows.find(x=>x.id===e.programId);return e.organizationId===person.organizationId&&(e.participantId===person.id||e.facilitatorId===person.id||e.createdBy===person.id||e.approvedBy===person.id||e.paidBy===person.id)&&can(viewer,'view','expenses',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:e.organizationId,self:self&&(e.participantId===person.id||e.facilitatorId===person.id),assigned:!!p&&p.facilitatorIds.includes(viewer.id),coFunded:!!p&&p.sponsorOrganizationIds?.includes(viewer.organizationId||'')});});
 const authoredStories=blogPosts.filter(p=>p.authorId===person.id&&(p.status==='published'||can(viewer,'view','blog',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:p.organizationId,assigned:!!p.programId&&visibleProgramRows.some(x=>x.id===p.programId&&x.facilitatorIds.includes(viewer.id))}))),organizedEvents=events.filter(e=>e.organizationId===person.organizationId&&e.organizerId===person.id&&(e.public&&e.status==='upcoming'||can(viewer,'view','events',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:e.organizationId})));
 const tabs=[{id:'overview',label:'Overview',icon:Users,show:true},{id:'programs',label:'Programs & activity',icon:BookOpen,show:programsAllowed},{id:'attendance',label:'Attendance',icon:CalendarDays,show:can(viewer,'view','attendance',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:orgId,self,assigned:personSessions.some(s=>s.facilitatorIds.includes(viewer.id))})},{id:'assessment',label:'Assessments',icon:Check,show:can(viewer,'view','assessments',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:orgId,self,assigned:personPrograms.some(p=>p.facilitatorIds.includes(viewer.id))})||can(viewer,'view','evaluations',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:orgId,self})},{id:'certificates',label:'Certificates',icon:Award,show:can(viewer,'view','certificates',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:orgId,self,assigned:personPrograms.some(p=>p.facilitatorIds.includes(viewer.id))})},{id:'finance',label:'Finance',icon:WalletCards,show:can(viewer,'view','expenses',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:orgId,self,assigned:personPrograms.some(p=>p.facilitatorIds.includes(viewer.id))})},{id:'content',label:'Content',icon:FileText,show:can(viewer,'view','blog',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:orgId})||can(viewer,'view','events',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:orgId})},{id:'reports',label:'Reports',icon:ClipboardList,show:can(viewer,'view','reports',{organizationId:viewer.organizationId||undefined,resourceOrganizationId:orgId,self})},{id:'activity-log',label:'Activity log',icon:Activity,show:viewerAdmin||self}].filter(t=>t.show);
 const completed=personAttendance.filter(a=>a.state==='present'||a.state==='late').length,attendanceRate=personAttendance.length?Math.round(completed/personAttendance.length*100):0;
 return <Modal title={`${person.name} · profile`} sub="A consolidated, permission-aware view of this person's workspace activity." onClose={onClose}><div className="profile360"><div className="profile360-hero"><span className="profile-avatar">{personPhotoAllowed(person)&&person.photoUrl?<img src={person.photoUrl} alt=""/>:person.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><h3>{person.name}</h3><p>{profileFields.includes('email')?person.email:'Contact details are restricted'} · {organizations.find(o=>o.id===person.organizationId)?.name||'Platform account'}</p><div className="profile360-tags">{profileFields.includes('status')&&<StatusBadge status={person.status}/>}{profileFields.includes('roles')&&person.roleIds.map(id=><Badge key={id}>{roles.find(r=>r.id===id)?.name||id}</Badge>)}</div></div></div><nav className="profile360-tabs" aria-label="User profile sections">{tabs.map(t=><button key={t.id} className={tab===t.id?'active':''} onClick={()=>setTab(t.id)}><t.icon size={14}/>{t.label}</button>)}</nav><div className="profile360-content">
 {tab==='overview'&&<><div className="profile360-metrics"><div><small>PROGRAMS & COHORTS</small><b>{visibleProgramRows.length}</b></div><div><small>ATTENDANCE RATE</small><b>{personAttendance.length?`${attendanceRate}%`:'—'}</b></div><div><small>CERTIFICATES</small><b>{personCertificates.length}</b></div><div><small>PROFILE COMPLETENESS</small><b>{derived.profileCompletenessPct}%</b></div>{profileFields.includes('training')&&<div><small>CPD CREDITS</small><b>{derived.cpdCreditsTotal}</b></div>}{profileFields.includes('engagement')&&<div><small>ENGAGEMENT</small><b>{derived.engagementScore}/100</b></div>}{profileFields.includes('facilitatorExtension')&&<div><small>FACILITATOR RATING</small><b>{derived.performanceRatingAvg??'—'}</b></div>}</div><div className="profile360-facts">{profileFields.includes('email')&&<div><small>EMAIL</small><b>{person.email}</b></div>}{profileFields.includes('organization')&&<div><small>ORGANIZATION</small><b>{organizations.find(o=>o.id===person.organizationId)?.name||'WeGo Platform'}</b></div>}{profileFields.includes('roles')&&<div><small>ASSIGNED ROLES</small><b>{person.roleIds.map(id=>roles.find(r=>r.id===id)?.name||id).join(' · ')}</b></div>}{profileFields.includes('status')&&<div><small>ACCOUNT STATUS</small><b><StatusBadge status={person.status}/></b></div>}{profileFields.includes('phone')&&person.primaryPhone&&<div><small>PHONE</small><b>{person.primaryPhone}</b></div>}</div>
 <section className="profile-section"><h3>Identity & contact</h3><div className="profile360-facts">{profileFields.includes('nationalId')&&person.nationalId&&<div><small>NATIONAL ID</small><b>{person.nationalId}</b></div>}{profileFields.includes('passportNumber')&&person.passportNumber&&<div><small>PASSPORT</small><b>{person.passportNumber}</b></div>}{profileFields.includes('professional')&&<><div><small>GENDER</small><b>{person.gender||'Not provided'}</b></div><div><small>REGION</small><b>{person.address?.region||'Not provided'}</b></div></>}</div></section>
 {profileFields.includes('professional')&&<section className="profile-section"><h3>Professional & education</h3><div className="profile360-facts"><div><small>SECTOR</small><b>{person.sector||'Not provided'}</b></div><div><small>EMPLOYMENT</small><b>{person.employmentStatus||'Not provided'}</b></div><div><small>EDUCATION</small><b>{person.highestEducationLevel||'Not provided'}</b></div><div><small>FIELD OF STUDY</small><b>{person.fieldOfStudy||'Not provided'}</b></div></div></section>}
 {profileFields.includes('demographics')&&<section className="profile-section"><h3>Demographics</h3><div className="profile360-facts"><div><small>NATIONALITY</small><b>{person.nationality||'Not provided'}</b></div><div><small>DISABILITY / ACCESSIBILITY</small><b>{person.disabilityStatus||person.accessibilityNeeds||'Not provided'}</b></div><div><small>HOUSEHOLD SIZE</small><b>{person.householdSize??'Not provided'}</b></div></div></section>}
 {profileFields.includes('financial')&&<section className="profile-section"><h3>Financial details</h3><div className="profile360-facts"><div><small>PAYMENT PREFERENCE</small><b>{person.paymentPreference||'Not provided'}</b></div><div><small>BANK / MOBILE MONEY</small><b>{person.bankAccountOrMobileMoney||'Not provided'}</b></div><div><small>TIN</small><b>{person.tin||'Not provided'}</b></div></div></section>}
 {profileFields.includes('emergencyContact')&&<section className="profile-section"><h3>Emergency contact</h3><p>{person.emergencyContact?.name||'Not provided'} · {person.emergencyContact?.phone||''}</p></section>}
 {profileFields.includes('facilitatorExtension')&&<section className="profile-section"><h3>Facilitator profile</h3><div className="profile360-facts"><div><small>EXPERTISE</small><b>{person.expertiseAreas?.join(', ')||'—'}</b></div><div><small>RATE</small><b>{person.facilitationRate?cash(person.facilitationRate):'—'}</b></div><div><small>AVAILABILITY</small><b>{person.availabilityCalendarRef?'Calendar on file':'—'}</b></div></div></section>}
 {profileFields.includes('staffExtension')&&<section className="profile-section"><h3>Organization staff</h3><div className="profile360-facts"><div><small>ROLE WITHIN ORGANIZATION</small><b>{person.roleWithinOrganization||'—'}</b></div><div><small>ACCESS LEVEL</small><b>{person.accessLevelApproved||person.accessLevelRequested||'—'}</b></div><div><small>DEPARTMENTS MANAGED</small><b>{person.departmentsManaged?.join(', ')||'—'}</b></div><div><small>JOINED</small><b>{person.dateJoinedPlatform||'—'}</b></div></div></section>}{profileFields.includes('consent')&&<section className="profile-section"><h3>Consent & compliance</h3><p>Privacy consent {person.dataPrivacyConsent?.agreed?'recorded':'not recorded'} · Photo/media consent {person.photoMediaConsent?.agreed?'recorded':'not recorded'}</p></section>}</>}
 {tab==='programs'&&<><section className="profile-section"><h3>Training history · {derived.trainingHistory.length} enrollments</h3><div className="profile360-facts"><div><small>CPD CREDIT TOTAL</small><b>{derived.cpdCreditsTotal}</b></div>{derived.trainingHistory.filter(item=>visibleProgramRows.some(p=>p.id===item.programId)).map(item=><div key={item.programId}><small>{item.status.toUpperCase()}</small><b>{item.programTitle}</b></div>)}</div></section><div className="table-scroll"><table><thead><tr><th>PROGRAM / ACTIVITY</th><th>CONTEXT ROLE</th><th>COHORT</th><th>STATUS</th></tr></thead><tbody>{visibleProgramRows.map(p=>{const enrollment=enrollments.find(e=>e.programId===p.id&&e.participantId===person.id),cohort=enrollment?cohorts.find(c=>c.id===enrollment.cohortId):cohorts.find(c=>c.programId===p.id);return <tr key={p.id}><td><b>{p.title}</b></td><td>{p.facilitatorIds.includes(person.id)?'Facilitator':'Participant'}</td><td>{cohort?.name||'—'}</td><td><StatusBadge status={enrollment?.status||cohort?.status||p.status}/></td></tr>})}</tbody></table>{visibleProgramRows.length===0&&<p className="empty-inline">No program or facilitation activity yet.</p>}</div></>}
 {tab==='attendance'&&<><div className="profile360-summary"><span>Attendance rate</span><b>{personAttendance.length?`${attendanceRate}%`:'No attendance records'}</b></div><div className="table-scroll"><table><thead><tr><th>SESSION</th><th>DATE</th><th>LEARNER / CONTEXT</th><th>STATUS</th></tr></thead><tbody>{personAttendance.map(a=>{const session=sessions.find(s=>s.id===a.sessionId);return <tr key={a.id}><td>{session?.title||'Training session'}</td><td>{session?.startsAt.slice(0,10)||'—'}</td><td>{session?.facilitatorIds.includes(person.id)?'Facilitator':'Participant'}</td><td><StatusBadge status={a.state}/></td></tr>})}</tbody></table>{personAttendance.length===0&&<p className="empty-inline">No attendance activity yet.</p>}</div></>}
 {tab==='assessment'&&<div className="table-scroll"><table><thead><tr><th>PROGRAM</th><th>TYPE</th><th>RESULT</th><th>DATE</th></tr></thead><tbody>{personAssessments.map(a=><tr key={a.id}><td>{programs.find(p=>p.id===a.programId)?.title||'Program'}</td><td>Assessment</td><td>{a.score}/{a.maxScore} · {a.passed?'Passed':'Review'}</td><td>{a.assessedAt}</td></tr>)}{personEvaluations.map(e=><tr key={e.id}><td>{programs.find(p=>p.id===e.programId)?.title||'Program'}</td><td>Evaluation</td><td>{e.rating}/5 rating</td><td>{e.submittedAt.slice(0,10)}</td></tr>)}</tbody></table>{personAssessments.length+personEvaluations.length===0&&<p className="empty-inline">No assessments or evaluations yet.</p>}</div>}
 {tab==='certificates'&&<div className="table-scroll"><table><thead><tr><th>CREDENTIAL</th><th>ISSUED</th><th>STATUS</th><th>SHARE</th></tr></thead><tbody>{personCertificates.map(c=><tr key={c.id}><td><a href={`/verify/${c.publicSlug}`} target="_blank" rel="noreferrer">{programs.find(p=>p.id===c.programId)?.title||'Certificate'} <ArrowUpRight size={13}/></a></td><td>{c.issuedAt}</td><td><StatusBadge status={c.status}/></td><td><Share url={`/verify/${c.publicSlug}`} title={`${person.name} · ${programs.find(p=>p.id===c.programId)?.title||'WeGo.org certificate'}`}/></td></tr>)}</tbody></table>{personCertificates.length===0&&<p className="empty-inline">No certificates issued yet.</p>}</div>}
 {tab==='finance'&&<div className="table-scroll"><table><thead><tr><th>DESCRIPTION</th><th>CATEGORY</th><th>DATE</th><th>AMOUNT</th><th>STATUS</th></tr></thead><tbody>{personExpenses.map(x=><tr key={x.id}><td>{x.description}</td><td>{x.category.replaceAll('_',' ')}</td><td>{x.incurredAt||'—'}</td><td>{cash(x.amountMinor,x.currency)}</td><td><StatusBadge status={x.status}/></td></tr>)}</tbody></table>{personExpenses.length===0&&<p className="empty-inline">No visible finance records for this account.</p>}</div>}
 {tab==='content'&&<div className="table-scroll"><table><thead><tr><th>CONTRIBUTION</th><th>TYPE</th><th>DATE / STATUS</th><th>LINK</th></tr></thead><tbody>{authoredStories.map(p=><tr key={p.id}><td>{p.title}</td><td>Story</td><td><StatusBadge status={p.status}/></td><td><a href={`/blog/${p.publicSlug}`} target="_blank" rel="noreferrer">Open <ArrowUpRight size={13}/></a></td></tr>)}{organizedEvents.map(e=><tr key={e.id}><td>{e.title}</td><td>Program event</td><td><StatusBadge status={e.status}/></td><td><a href={`/events/${e.publicSlug}`} target="_blank" rel="noreferrer">Open <ArrowUpRight size={13}/></a></td></tr>)}</tbody></table>{authoredStories.length+organizedEvents.length===0&&<p className="empty-inline">No content contributions yet.</p>}</div>}
 {tab==='reports'&&<div className="profile360-report"><div className="profile360-metrics"><div><small>ASSOCIATED LEARNERS</small><b>{new Set(enrollments.filter(e=>visibleProgramRows.some(p=>p.id===e.programId)).map(e=>e.participantId)).size}</b></div><div><small>PROGRAM OUTCOMES</small><b>{visibleProgramRows.filter(p=>p.status==='completed').length} completed programs</b></div></div><p className="subdued">No saved person-specific reports are attached yet. This summary reflects visible program participation and delivery data.</p></div>}
 {tab==='activity-log'&&<div className="activity-timeline">{accountActivity.filter(a=>a.userId===person.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(a=><article key={a.id}><span className="activity-dot"/><div><b>{a.event.replaceAll('_',' ')}</b><p>{a.details}</p><small>{new Date(a.createdAt).toLocaleString()}</small></div></article>)}{!accountActivity.some(a=>a.userId===person.id)&&<p className="empty-inline">No account activity has been recorded yet.</p>}</div>}
 </div></div></Modal>;
}
